const team = [
  {
    name: 'Venusaur',
    species: 'venusaur',
    gender: 'M',
    moves: [
      { id: 'sleeppowder', pp: 15 },
      { id: 'sludgebomb', pp: 10 },
      { id: 'leafstorm', pp: 5 },
      { id: 'protect', pp: 10 },
    ],
    ability: 'chlorophyll',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'widelens',
    level: 50,
    shiny: false,
    nature: 'timid',
  },
  {
    name: 'Torkoal',
    species: 'torkoal',
    gender: 'M',
    moves: [
      {id: 'eruption', pp: 5 },
      {id: 'heatwave', pp: 10 },
      {id: 'solarbeam', pp: 10 },
      {id: 'earthpower', pp: 10 },
    ],
    ability: 'drought',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'charcoal',
    level: 50,
    shiny: false,
    nature: 'quiet',
  },
  {
    name: 'Conkeldurr',
    species: 'conkeldurr',
    gender: 'M',
    moves: [
      { id: 'machpunch', pp: 30 },
      { id: 'drainpunch', pp: 10 },
      { id: 'icepunch', pp: 15 },
      { id: 'protect', pp: 10 },
    ],
    ability: 'ironfist',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'lifeorb',
    level: 50,
    shiny: false,
    nature: 'adamant',
  },
  {
    name: 'Hatterene',
    species: 'hatterene',
    gender: 'F',
    moves: [
      { id: 'dazzlinggleam', pp: 10 },
      { id: 'psychic', pp: 10 },
      { id: 'trickroom', pp: 5 },
      { id: 'protect', pp: 10 },
    ],
    ability: 'magicbounce',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'focussash',
    level: 50,
    shiny: false,
    nature: 'quiet',
  },
  {
    name: 'Incineroar',
    species: 'incineroar',
    gender: 'M',
    moves: [
      { id: 'fakeout', pp: 10 },
      { id: 'flareblitz', pp: 15 },
      { id: 'partingshot', pp: 20 },
      { id: 'darkestlariat', pp: 10 },
    ],
    ability: 'intimidate',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'assaultvest',
    level: 50,
    shiny: false,
    nature: 'careful',
  },
  {
    name: 'Dusclops',
    species: 'dusclops',
    gender: 'M',
    moves: [
      { id: 'trickroom', pp: 5 },
      { id: 'nightshade', pp: 15 },
      { id: 'painsplit', pp: 20 },
      { id: 'willowisp', pp: 15 },
    ],
    ability: 'frisk',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'eviolite',
    level: 50,
    shiny: false,
    nature: 'relaxed',
  },
];

module.exports = team;
